/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthLeftSide: typeof import('./src/components/auth/left-side.vue')['default']
    AuthRightSide: typeof import('./src/components/auth/right-side.vue')['default']
    CartHeader: typeof import('./src/components/CartHeader.vue')['default']
    CartPage: typeof import('./src/components/CartPage.vue')['default']
    CartStore: typeof import('./src/components/CartStore.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconsIconGooglePlay: typeof import('./src/components/icons/IconGooglePlay.vue')['default']
    IconsIconLogoBlue: typeof import('./src/components/icons/IconLogoBlue.vue')['default']
    IconsIconLogoGrey: typeof import('./src/components/icons/IconLogoGrey.vue')['default']
    IconsIconQR: typeof import('./src/components/icons/IconQR.vue')['default']
    IconsIconTelegram: typeof import('./src/components/icons/IconTelegram.vue')['default']
    IconsIconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconsIconTwitter: typeof import('./src/components/icons/IconTwitter.vue')['default']
    IconsIconVk: typeof import('./src/components/icons/IconVk.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/footer.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/header.vue')['default']
    ProductItem: typeof import('./src/components/ProductItem.vue')['default']
    ProductsList: typeof import('./src/components/products-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
